"""Opt-in native-agent runtime for typed, durable agent methods.

The package exposes contracts and storage primitives without performing I/O or
registering callbacks at import time. The callback entry point lives in
``register_callbacks.py`` and is intentionally disabled by default.
"""

from .contracts import (
    AuthorizationDecision,
    CapabilityEffect,
    CapabilitySpec,
    ContextBlock,
    ContextBudget,
    EventQuery,
    EventSummary,
    ExecutionIdentity,
    MethodSpec,
    NativeEvent,
    NativeEventKind,
    NativeExecutionRecord,
    NativeExecutionStatus,
    NativeStateEnvelope,
    NativeStrategyName,
    ReferenceHandle,
    ReferencePreview,
    SearchCountRequest,
    SearchCounts,
    SearchHandleResult,
    SearchMatch,
    SearchPage,
    SearchPageRequest,
    SearchPathCount,
    SearchPrefixRequest,
    SearchResultSet,
    SearchSampleRequest,
)
from .events import EventService, EventStore
from .errors import (
    CapabilityDeniedError,
    CapabilityNotFoundError,
    CapabilityValidationError,
    EventStoreError,
    HandleUnavailableError,
    NativeAgentError,
    NativeContractError,
    NativeOutputValidationError,
    NativeRuntimeDisabledError,
    NativeStorageUnavailableError,
    StateConflictError,
    StateSchemaError,
)

__all__ = [
    "AuthorizationDecision",
    "CapabilityDeniedError",
    "CapabilityEffect",
    "CapabilityNotFoundError",
    "CapabilitySpec",
    "CapabilityValidationError",
    "ContextBlock",
    "ContextBudget",
    "EventQuery",
    "EventService",
    "EventStore",
    "EventStoreError",
    "EventSummary",
    "ExecutionIdentity",
    "HandleUnavailableError",
    "MethodSpec",
    "NativeAgentError",
    "NativeContractError",
    "NativeEvent",
    "NativeEventKind",
    "NativeExecutionRecord",
    "NativeExecutionStatus",
    "NativeOutputValidationError",
    "NativeRuntimeDisabledError",
    "NativeStateEnvelope",
    "NativeStorageUnavailableError",
    "NativeStrategyName",
    "ReferenceHandle",
    "ReferencePreview",
    "SearchCountRequest",
    "SearchCounts",
    "SearchHandleResult",
    "SearchMatch",
    "SearchPage",
    "SearchPageRequest",
    "SearchPathCount",
    "SearchPrefixRequest",
    "SearchResultSet",
    "SearchSampleRequest",
    "StateConflictError",
    "StateSchemaError",
]
